name: Merge me test dependencies!

on: # zizmor: ignore[dangerous-triggers] intentional: this workflow runs in the context of the base branch
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions: {}

jobs:
  automerge:
    permissions: {}
    uses: fizyk/actions-reuse/.github/workflows/shared-automerge.yml@ae6177442c58a91f60ffaf7f7a90a331aaf3b049 # v5.4.1
    secrets:
      client_id: ${{ secrets.MERGE_APP_CLIENT_ID }}
      private_key: ${{ secrets.MERGE_APP_PRIVATE_KEY }}
