name: Merge me test dependencies!

on: # zizmor: ignore[dangerous-triggers] intentional: this workflow runs in the context of the base branch
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions: {}

jobs:
  automerge:
    permissions: {}
    uses: fizyk/actions-reuse/.github/workflows/shared-automerge.yml@432d7575c4cc00724bb43d408cc75e2830c51ae2 # v5.9.0
    secrets:
      client_id: ${{ secrets.MERGE_APP_CLIENT_ID }}
      private_key: ${{ secrets.MERGE_APP_PRIVATE_KEY }}
