name: Merge me test dependencies!

on: # zizmor: ignore[dangerous-triggers] intentional: this workflow runs in the context of the base branch
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions: {}

jobs:
  automerge:
    permissions: {}
    uses: fizyk/actions-reuse/.github/workflows/shared-automerge.yml@7eefbd6ffc6c6787ad3be6ce93dcf475e3ae99b5 # v5.6.0
    secrets:
      client_id: ${{ secrets.MERGE_APP_CLIENT_ID }}
      private_key: ${{ secrets.MERGE_APP_PRIVATE_KEY }}
