name: Test build package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_call:

permissions: {}

jobs:
  build:
    uses: fizyk/actions-reuse/.github/workflows/shared-pypi.yml@432d7575c4cc00724bb43d408cc75e2830c51ae2 # v5.9.0
    with:
      dependency-manager: uv
