name: Test build package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_call:

permissions: {}

jobs:
  build:
    uses: fizyk/actions-reuse/.github/workflows/shared-pypi.yml@2ab3c94b032a11fca1238ef134690e589616739d # v5.7.0
    with:
      dependency-manager: uv
