name: Run linters

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  lint:
    uses: fizyk/actions-reuse/.github/workflows/linters-python.yml@v2.5.1
    with:
      mypy: true
      ruff: true
      black: true