name: Run test commands

on:
  pull_request:
    branches: [ master ]

permissions: {}

jobs:
  pr-check:
    uses: fizyk/actions-reuse/.github/workflows/shared-pr-check.yml@a910bc71a0ba28e2d6c5c458df0719e093988e7f # v5.10.0
    with:
      dependency-manager: uv
