name: Run test commands

on:
  pull_request:
    branches: [ master ]

jobs:
  pr-check:
    uses: fizyk/actions-reuse/.github/workflows/shared-pr-check.yml@7967e3c28fb64f67f6f58d19a4e070da14070932 # v5.2.0
    with:
      dependency-manager: uv
