name: Run test commands

on:
  pull_request:
    branches: [ master ]

permissions: {}

jobs:
  pr-check:
    uses: fizyk/actions-reuse/.github/workflows/shared-pr-check.yml@432d7575c4cc00724bb43d408cc75e2830c51ae2 # v5.9.0
    with:
      dependency-manager: uv
