name: Run linters

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions: {}

jobs:
  pre-commit:
    uses: fizyk/actions-reuse/.github/workflows/shared-pre-commit.yml@42b61e053c1d70a61deb42b323c1a2229e2e7fe0 # v5.5.0
