name: Run linters

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  pre-commit:
    uses: fizyk/actions-reuse/.github/workflows/shared-pre-commit.yml@a705c3602adb3ef95f7f4bdf81dcacd3a136d86e # v5.0.0
