name: Package and publish
on:
  push:
    tags:
      - v*
jobs:
  build:
    uses: fizyk/actions-reuse/.github/workflows/shared-pypi.yml@14e008c246b7b8eeab7cb5c543117471fee37310 # v5.1.2
    with:
      publish: false
      dependency-manager: uv

  publish:
    name: Publish Python 🐍 distributions 📦 to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Download distributions 📦
        uses: actions/download-artifact@v8
        with:
          name: package
          path: dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1.14.0
        with:
          verbose: true
