name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version to be added'
        required: true
        type: string

permissions: {}

jobs:
  release:
    permissions:
      contents: read
    uses: fizyk/actions-reuse/.github/workflows/shared-release.yml@ae6177442c58a91f60ffaf7f7a90a331aaf3b049 # v5.4.1
    with:
      version: ${{ inputs.version }}
      dependency-manager: 'uv'
    secrets:
      app_id: ${{ secrets.RELEASE_APP_ID }}
      private_key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
