name: Scheduled release

on:
  schedule:
    - cron: '32 7 5 * *'
  workflow_dispatch: {}

concurrency:
  group: release-schedule

jobs:
  schedule:
    permissions:
      contents: read
    uses: fizyk/actions-reuse/.github/workflows/shared-release-schedule.yml@a910bc71a0ba28e2d6c5c458df0719e093988e7f # v5.10.0
    with:
      dependency-manager: 'uv'
      newsfragments-required: true
      minor-fragments: 'feature,depr'
      major-fragments: 'break'
    secrets:
      app_id: ${{ secrets.RELEASE_APP_ID }}
      private_key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
