name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    uses: fizyk/actions-reuse/.github/workflows/shared-tests-pytests.yml@f35c0eab43b88cb5f67a8519eb6dea27146f2145 # v5.2.4
    with:
      python-versions: '["3.10", "3.11", "3.12", "3.13", "3.14", "3.15", "pypy3.11"]'
      dependency-manager: uv
  tests-macos:
    needs:
      - tests
    uses: fizyk/actions-reuse/.github/workflows/shared-tests-pytests.yml@f35c0eab43b88cb5f67a8519eb6dea27146f2145 # v5.2.4
    with:
      python-versions: '["3.10", "3.11", "3.12", "3.13", "3.14", "3.15", "pypy3.11"]'
      dependency-manager: uv
      os: macos-latest
  tests-windows:
    needs:
      - tests
    uses: fizyk/actions-reuse/.github/workflows/shared-tests-pytests.yml@f35c0eab43b88cb5f67a8519eb6dea27146f2145 # v5.2.4
    with:
      python-versions: '["3.10", "3.11", "3.12", "3.13", "3.14", "3.15", "pypy3.11"]'
      dependency-manager: uv
      os: windows-latest
      env: '{"PYTHONTRACEMALLOC": 20}'
