name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    uses: fizyk/actions-reuse/.github/workflows/shared-tests-pytests.yml@a705c3602adb3ef95f7f4bdf81dcacd3a136d86e # v5.0.0
    with:
      python-versions: '["3.10", "3.11", "3.12", "3.13", "3.14", "pypy3.11"]'
      dependency-manager: uv
  tests-macos:
    needs:
      - tests
    uses: fizyk/actions-reuse/.github/workflows/shared-tests-pytests.yml@a705c3602adb3ef95f7f4bdf81dcacd3a136d86e # v5.0.0
    with:
      python-versions: '["3.10", "3.11", "3.12", "3.13", "3.14", "pypy3.11"]'
      dependency-manager: uv
      os: macos-latest
  tests-windows:
    needs:
      - tests
    uses: fizyk/actions-reuse/.github/workflows/shared-tests-pytests.yml@a705c3602adb3ef95f7f4bdf81dcacd3a136d86e # v5.0.0
    with:
      python-versions: '["3.10", "3.11", "3.12", "3.13", "3.14", "pypy3.11"]'
      dependency-manager: uv
      os: windows-latest
      env: '{"PYTHONTRACEMALLOC": 20}'
