name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    uses: fizyk/actions-reuse/.github/workflows/tests-pytests.yml@v2.2.1
    with:
      python-versions: '["3.8", "3.9", "3.10", "3.11", "pypy-3.8"]'
      pipenv-install-options: --skip-lock
  tests-macos:
    needs:
      - tests
    uses: fizyk/actions-reuse/.github/workflows/tests-pytests.yml@v2.2.1
    with:
      python-versions: '["3.8", "3.9", "3.10", "3.11", "pypy-3.8"]'
      os: macos-latest
      pipenv-install-options: --skip-lock
